CREATE TABLE customer (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name          VARCHAR2(100) NOT NULL,
    email         VARCHAR2(100) NOT NULL,
    phone         VARCHAR2(20)  NOT NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP,

    -- ✅ Primary Key
    CONSTRAINT pk_customer PRIMARY KEY (id),

    -- ✅ Composite Unique Constraint
    CONSTRAINT uq_customer_email_phone UNIQUE (email, phone)
);

CREATE TABLE address (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY,
    customer_id     NUMBER NOT NULL,
    address_type    VARCHAR2(20), -- HOME, OFFICE, OTHER
    address_line1   VARCHAR2(255) NOT NULL,
    address_line2   VARCHAR2(255),
    city            VARCHAR2(100) NOT NULL,
    state           VARCHAR2(100) NOT NULL,
    pincode         VARCHAR2(20)  NOT NULL,
    country         VARCHAR2(100) NOT NULL,
    is_default      NUMBER(1) DEFAULT 0,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP,
    -- ✅ Primary Key
    CONSTRAINT pk_address PRIMARY KEY (id),
    -- ✅ Foreign Key
    CONSTRAINT fk_address_customer
        FOREIGN KEY (customer_id)
        REFERENCES customer(id)
        ON DELETE CASCADE
);